source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CameraKit_Example', :exclusive => true do
  pod "CameraKit", :path => "../"
end

target 'CameraKit_Tests', :exclusive => true do
  pod "CameraKit", :path => "../"

  
end
